### PR TITLE
Added multi guard Implementation

### PR DESCRIPTION
**Pull request by iotronlab**
added a ContextManager object extending filament manager recieves the auth guard set in context config.

### CODE REVIEW

**Comment by coleshirley** [comment]
I've had a busy few weeks at work so I'm just not getting around to reviewing this PR. I can't accept the current changes because using a static $config property on the ContextManager can lead to unexpected behavior since any time it is changed it will affect every registered context.

I saw you submitted your own package to the community so I will close this PR since it seems you wrote your own solution that works for your project and I haven't gotten any other requests for this functionality

**Comment by iotronlab** [comment]
> I've had a busy few weeks at work so I'm just not getting around to reviewing this PR. I can't accept the current changes because using a static $config property on the ContextManager can lead to unexpected behavior since any time it is changed it will affect every registered context.
> 
> I saw you submitted your own package to the community so I will close this PR since it seems you wrote your own solution that works for your project and I haven't gotten any other requests for this functionality

I have tried to implement the context manager from your package v1 into v2. The $config is replacement of this lines. The $config is needed to get the guard from the context-config.php. Can you kindly suggest a way to implement this feature from v1 into v2?

```
protected static ?string $auth = null;

public static function getAuth(): ?Guard
    {
        return static::$auth ? auth()->guard(static::$auth) : null;
    }

public function auth(): Guard
    {
        return static::getAuth() ?? auth()->guard(config('filament.auth.guard'));
    }

```
I had to make my own package out of neccesity as this was a most wanted feature in filament (according to twitter polls) and there was several requests on the discord forum as well.

**Comment by coleshirley** [comment]
@iotronlab check out this PR and see if it does what you expect it to https://github.com/artificertech/filament-multi-context/pull/28

**Comment by iotronlab** [comment]
> @iotronlab check out this PR and see if it does what you expect it to #28

Sorry for the late reply. I had been buried alive in work. I checked the PR and it returns the correct guard, but we need a few more things to get the whole multi-guard system working.

1. Auth middleware and login page
2. Login and logout routes
3. UserMenuItem Logout

I can add them through a PR if you want. I have already implemented them.

**Pull request closed without merging**
